### ISSUE TITLE
Cannot run leetcode-sql-unlocked any more

### ISSUE THREAD

**Issue by joehou1988** [jjjchens235/leetcode-sql-unlocked#2]
Hi,

First, I would love to thank you for putting this together. I have been using it for weeks and it was working. However, last week, when I tried to use it again, it shows the error that 

Traceback (most recent call last):
  File "leetcode_sql_unlocked.py", line 77, in <module>
    main()
  File "leetcode_sql_unlocked.py", line 53, in main
    lc = get_leetcode()
  File "leetcode_sql_unlocked.py", line 49, in get_leetcode
    lc = Leetcode(driver_path, q_elements_path, q_state_path, q_public_urls_path, headless=headless)
  File "/Users/jq41/Documents/Python/python3/leetcode-sql-unlocked-master/leetcode_sql_unlocked/src/leetcode.py", line 39, in __init__
    self.question_nodes = QuestionNodes(q_elements, self.question_log.q_state['current'])
  File "/Users/jq41/Documents/Python/python3/leetcode-sql-unlocked-master/leetcode_sql_unlocked/src/questions.py", line 25, in __init__
    self.__current = self.create_q_nodes(question_elements, curr_log_num)
  File "/Users/jq41/Documents/Python/python3/leetcode-sql-unlocked-master/leetcode_sql_unlocked/src/questions.py", line 36, in create_q_nodes
    for q_num in question_elements.keys():
AttributeError: 'NoneType' object has no attribute 'keys'

I tried to run the test file and it gives similar error, saying that "Could not find question elements from leetcode.com
E". Is it related to the leetcode website update?

Thanks

**Comment by jjjchens235** [comment]
Thanks for bringing this to my attention. Yes, it has to do with the new leetcode website update. 

I'm currently incredibly busy till August, but if I have a chance I will try to implement a fix sooner than that.

**Comment by joehou1988** [comment]
Thanks a lot for your reply!

Anyway, thank you so much for all your effort.

Wish you the best,

**Comment by jjjchens235** [comment]
The code has been updated and the issue should be fixed. Thanks again for bringing this to my attention.

**Comment by Life-is-Smile-Always** [comment]
Hi, thanks for your effort .

But the recent update doesn't work for me, nothing appeared after clicking 'leetcode_sql_unlocked'.

**Comment by jjjchens235** [comment]
Can you include the traceback, please?
What do you mean nothing appeared after clicking ? What exactly did you click?

**Comment by Life-is-Smile-Always** [comment]
> Can you include the traceback, please?
> What do you mean nothing appeared after clicking ? What exactly did you click?

Hi, I cannot show you the traceback because the python program window only appeared just one second before disappeared again.

I have followed the instructions given, 1st run the setup.py file then run leetcode_sql_unlocked/leetcode_sql_unlocked.py. 
Thing was okay before leetcode update their questions bank and I have been using for around 1 month.
